port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: "jdbc:h2:mem:squad2"
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa.hibernate.ddl-auto: create


spring.mvc.dispatch-options-request: true

security.oauth2.client:
  client-id: "squad2"
  client-secret: "secret"
  scope: "password"
  grant-type: "password"
